import React from "react";
import Button from "react-bootstrap/Button";
import Modal from "react-bootstrap/Modal";
import Accordion from "react-bootstrap/Accordion";

const items = [
  {
    header: "Overview",
    body: `Advances in geoprocessing capacity have led to increased demand for
      and more widespread access to predictive ecological maps than ever
      before. An important motivation for building predictive ecological
      models, in addition to production of maps, is to understand the
      mechanistic drivers of the observed patterns. Comprehensive
      understanding of these models and effective application of
      predictive ecological maps to real-world problems requires tools
      for visualizing relationships between model predictions and their
      drivers. This is especially true when complex modeling frameworks,
      such as machine learning, are used. Currently, few tools exist to
      aid users of predictive ecological maps in this process of concurrent
      exploration of the spatial, geographic, and mechanistic relationships
      between prediction surfaces and their underlying drivers, resulting
      in a “black box” effect. This web portal was developed specifically 
      to address this gap by linking predictive ecological maps, geographic
      biophysical data, and a toolset for exploring and visualizing the
      modeled relationships between map predictions and their underlying
      biophysical drivers.`,
  },
  {
    header: "Purpose",
    body: `The EcoVis tool is designed to provide a data access and download
      platform for predictive maps of ecological phenomena generated by
      the LCSRG, dynamic mapping and exploration, and visualization tools
      that facilitate understanding of the biophysical predictors of the
      probability surfaces. EcoVis was developed originally for, and
      currently features, predictive maps of fire refugia, and fire
      severity, more generally. Fire refugia are an important legacy of
      wildfires and a key component of post-fire recovery, resilience to
      future disturbance, and many ecosystem services. Using boosted
      regression tree models and a suite of topographic, vegetation, fire
      behavior, fire weather, and climatic variables, we have developed
      predictive maps of fire refugia, and other types of fire severity
      (e.g. high severity fire) for forests of the Pacific Northwest,
      based on fires occurring in the region from 2002-2017. EcoVis allows
      the user to select from a list of predictive fire severity maps
      (refugia, non stand-replacing, or high-severity), explore and/or
      download these maps, view the predictions side-by-side with the
      underlying geospatial data inputs, and examine the modeled
      relationships between the severity predictions and their drivers.`,
  },
  {
    header: "Background",
    body: `An advantage of machine learning models is their ability to account
      for complex, non-linear relationships that are widespread in
      ecology. But this can make them challenging to understand, leading
      to a black box effect, and confounding interpretations of what
      factors lead to specific predictions for different points in the
      landscape. This tool therefore allows exploration of and access to
      the predictive maps from our models, but it also features a unique
      visualization tool, the Model Inspection Window, that permits
      detailed exploration of the underlying predictor variable maps and
      response functions that describe how predictions are influenced each
      predictor variable.`,
  },
  {
    header: "Probability surface maps",
    body: `The raster maps available on EcoVis consist of pixel-level model
      predictions that, together, describe the probability surface for
      each variable of interest. The predictions range from 0 (low
      probability) to 1 (high probability). These maps are useful for
      understanding large- or fine-scale patterns in the likelihood of a
      phenomenon, given any specific set of conditions.`,
  },
  {
    header: "Drivers/predictors",
    body: `Model predictions are based on a suite of time-invariant (spatial)
      and time-varying (spatio-temporal) predictors. The time-invariant
      predictor surfaces, such as topography, are fixed and require no
      input from the user. However, time-varying predictors, such as fire
      weather or climate, can fluctuate and require user input to tune
      these dials to the levels desired for each map. EcoVis allows the
      two most influential time-varying predictors for any model to be set
      to low (10th percentile), moderate (50th percentile), or extreme
      (90th percentile) conditions. This functionality permits the user to
      observe changes in the spatial patterns of predicted fire severity
      under a range of conditions, to examine why these changes occur
      based on the modeled relationships between each driver and the
      modeled probability, and to explore the spatial and geographic
      patterns of the underlying predictor variables side-by-side with the
      predictions.`,
  },
];

export default function IntroductionPanel({ show, onHide }) {
  return (
    <Modal show={show} onHide={onHide} size="xl">
      <Modal.Header closeButton>
        <Modal.Title>EcoVis Tool</Modal.Title>
      </Modal.Header>

      <Modal.Body>
        <Accordion defaultActiveKey="0" flush>
          {items.map((item, idx) => (
            <Accordion.Item key={idx} eventKey={`"${idx}"`}>
              <Accordion.Header>{item.header}</Accordion.Header>
              <Accordion.Body>{item.body}</Accordion.Body>
            </Accordion.Item>
          ))}
        </Accordion>
      </Modal.Body>

      <Modal.Footer>
        <Button variant="primary" onClick={onHide}>
          Close
        </Button>
      </Modal.Footer>
    </Modal>
  );
}
